### ISSUE TITLE
"View document" broken

### ISSUE THREAD

**Issue by crisptofuring** [keepid/keepid_client#47]
![Screenshot (11)](https://user-images.githubusercontent.com/5490025/94513967-086ae700-01ee-11eb-8e90-3044e5ae67b1.png)
Click "view document"
![Screenshot (12)](https://user-images.githubusercontent.com/5490025/94513970-09037d80-01ee-11eb-99ad-5fac6f7d9944.png)
Leads to broken page error saying "this content is blocked."

**Comment by JohnBaek-wr** [comment]
Now this is interesting, because I can't even see my documents.

**Comment by crchong1** [comment]
this is fixed btw

**Comment by JohnBaek-wr** [comment]
![image](https://user-images.githubusercontent.com/65623389/94751708-2f90f800-0357-11eb-9472-d16230876203.png)

Logged in as Wormtongue (Client) just now, turned off adblocker and allowed cookies, still shows this?
